spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: devqoo-backend
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
