spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: devqoo-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
