spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: devqoo-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
springdoc:
  api-docs:
    path: /api-docs
