server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_URI}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
