SET search_path TO public;

-- 기존 테이블 삭제
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS USERS;

-- 기존 인덱스 삭제
DROP INDEX IF EXISTS IDX_COMMENTS_USER_ID;
DROP INDEX IF EXISTS IDX_COMMENTS_POST_ID;
DROP INDEX IF EXISTS IDX_POSTS_USER_ID;
DROP INDEX IF EXISTS IDX_POSTS_CATEGORY_ID;


-- 유저 테이블
CREATE TABLE USERS (
   USER_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   NICKNAME    VARCHAR(20) NOT NULL,
   EMAIL       VARCHAR(50) NOT NULL,
   PASSWORD    VARCHAR(255) NOT NULL,
   ROLE        VARCHAR(10) NOT NULL,
   CREATED_AT  TIMESTAMP NOT NULL,
   UPDATED_AT  TIMESTAMP NOT NULL
);

COMMENT ON COLUMN USERS.USER_ID IS '유저 아이디';
COMMENT ON COLUMN USERS.NICKNAME IS '닉네임';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USERS.ROLE IS '권한 (강사 : teacher / 멘토 : mentor / 수강생 : student)';
COMMENT ON COLUMN USERS.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN USERS.UPDATED_AT IS '수정 일시';


-- 카테고리 테이블
CREATE TABLE CATEGORIES (
    CATEGORY_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME   VARCHAR(50) NOT NULL,
    CREATED_AT      TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP NOT NULL
);

COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS '카테고리 아이디';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS '카테고리명';
COMMENT ON COLUMN CATEGORIES.CREATED_AT IS '생성일시';
COMMENT ON COLUMN CATEGORIES.UPDATED_AT IS '수정일시';


-- 게시글 테이블
CREATE TABLE POSTS (
   POST_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   CATEGORY_ID     BIGINT NOT NULL,
   USER_ID         BIGINT NOT NULL,
   POST_TITLE      VARCHAR(100) NOT NULL,
   CONTENT         TEXT NOT NULL,
   VIEW_COUNT      INTEGER DEFAULT 0 NOT NULL,
   CREATED_AT      TIMESTAMP NOT NULL,
   UPDATED_AT      TIMESTAMP NOT NULL
);

COMMENT ON COLUMN POSTS.POST_ID IS '게시글 아이디';
COMMENT ON COLUMN POSTS.CATEGORY_ID IS 'CATEGORY_ID 식별';
COMMENT ON COLUMN POSTS.USER_ID IS 'USER_ID 식별';
COMMENT ON COLUMN POSTS.POST_TITLE IS '제목';
COMMENT ON COLUMN POSTS.CONTENT IS '내용';
COMMENT ON COLUMN POSTS.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN POSTS.CREATED_AT IS '생성일시';
COMMENT ON COLUMN POSTS.UPDATED_AT IS '수정일시';

-- INDEX 생성
CREATE INDEX IDX_POSTS_CATEGORY_ID ON POSTS(CATEGORY_ID);
CREATE INDEX IDX_POSTS_USER_ID ON POSTS(USER_ID);


-- 댓글 테이블
CREATE TABLE COMMENTS (
  COMMENT_ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  POST_ID         BIGINT NOT NULL,
  USER_ID         BIGINT NOT NULL,
  CONTENT         VARCHAR(500) NOT NULL,
  CREATED_AT      TIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP NOT NULL
);

COMMENT ON COLUMN COMMENTS.COMMENT_ID IS '댓글 아이디';
COMMENT ON COLUMN COMMENTS.POST_ID IS 'POST_ID 식별';
COMMENT ON COLUMN COMMENTS.USER_ID IS 'USER_ID 식별';
COMMENT ON COLUMN COMMENTS.CONTENT IS '내용';
COMMENT ON COLUMN COMMENTS.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN COMMENTS.UPDATED_AT IS '수정 일시';

-- INDEX 생성
CREATE INDEX IDX_COMMENTS_POST_ID ON COMMENTS(POST_ID);
CREATE INDEX IDX_COMMENTS_USER_ID ON COMMENTS(USER_ID);